name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: program1.py
      id: program1-py
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: sudo -H pip3 install pytest
    - name: program2.py
      id: program2-py
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        PROGRAM1-PY_RESULTS: "${{steps.program1-py.outputs.result}}"
        PROGRAM2-PY_RESULTS: "${{steps.program2-py.outputs.result}}"
      with:
        runners: program1-py,program2-py
